---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: name=mysql-server
    - apt: name=memcached
    - copy: src=../files/etc/mysql/my.cnf dest=/etc/mysql/my.cnf owner=root mode=644
      notify: reload mysql
  handlers:
    - name: reload mysql
      shell: sudo /etc/init.d/mysql restart
