---
- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.3.0 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /.local/ruby/bin/gem install bundler
      args:
        creates: /home/isucon/.local/ruby/bin/bundle
