- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    # google driveにあります。
    # https://drive.google.com/open?id=1iRKgcSl6PDpSStea0qxFZqjwSLY7PHzr
    - name: copy mysqldump
      copy: src=../files/home/isucon/backup/dump.sql.bz2 dest=/home/isucon/backup/mysqldump.sql.bz2 owner=isucon mode=755
    - name: create database
      shell: bzcat /home/isucon/backup/mysqldump.sql.bz2 | mysql -u root
